/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.controlador.ControladorAlumno;
import ec.edu.controlador.ControladorCurso;
import ec.edu.controlador.ControladorDocente;
import ec.edu.controlador.ControladorRector;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author ariel
 */
public class VentanaGeneral extends javax.swing.JFrame {
    
    private ControladorRector controladorRector;
    private ControladorDocente controladorDocente;
    private ControladorAlumno controladorAlumno;
    private ControladorCurso controladorCurso;
    
    private VentanaGestionDocentes ventanaGestionDocentes;
    private VentanaRegistroDocente ventanaRegistroDocente;

    public VentanaGeneral(ControladorRector controladorRector, ControladorDocente controladorDocente, ControladorAlumno controladorAlumno, ControladorCurso controladorCurso) {
        initComponents();
        
        this.controladorRector = controladorRector;
        this.controladorDocente = controladorDocente;
        this.controladorAlumno = controladorAlumno;
        this.controladorCurso = controladorCurso;
        
        ventanaGestionDocentes = new VentanaGestionDocentes(controladorDocente);
        ventanaRegistroDocente = new VentanaRegistroDocente(controladorDocente);
    }

    public JMenuItem getJMenuItemActualizarDatos() {
        return JMenuItemActualizarDatos;
    }

    public void setJMenuItemActualizarDatos(JMenuItem JMenuItemActualizarDatos) {
        this.JMenuItemActualizarDatos = JMenuItemActualizarDatos;
    }

    public JMenu getjMenuGestionActividades() {
        return jMenuGestionActividades;
    }

    public JMenu getjMenuGestionAlumnos() {
        return jMenuGestionAlumnos;
    }

    public JMenu getjMenuGestionClases() {
        return jMenuGestionClases;
    }

    public JMenu getjMenuGestionDocentes() {
        return jMenuGestionDocentes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneEscritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        JMenuInicio = new javax.swing.JMenu();
        jMenuGestionDocentes = new javax.swing.JMenu();
        jMenuItemAgregarDocente = new javax.swing.JMenuItem();
        jMenuItemDocentesRegistrados = new javax.swing.JMenuItem();
        jMenuGestionClases = new javax.swing.JMenu();
        jMenuGestionAlumnos = new javax.swing.JMenu();
        jMenuGestionActividades = new javax.swing.JMenu();
        JMenuItemSalir = new javax.swing.JMenuItem();
        JMenuAjustes = new javax.swing.JMenu();
        JMenuItemCambiarColor = new javax.swing.JMenuItem();
        JMenuAdministrar = new javax.swing.JMenu();
        JMenuItemActualizarDatos = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItemEliminarCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneEscritorioLayout = new javax.swing.GroupLayout(jDesktopPaneEscritorio);
        jDesktopPaneEscritorio.setLayout(jDesktopPaneEscritorioLayout);
        jDesktopPaneEscritorioLayout.setHorizontalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPaneEscritorioLayout.setVerticalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        JMenuInicio.setMnemonic('f');
        JMenuInicio.setText("Inicio");

        jMenuGestionDocentes.setText("Gestionar Docentes");

        jMenuItemAgregarDocente.setText("Agregar Docente");
        jMenuItemAgregarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarDocenteActionPerformed(evt);
            }
        });
        jMenuGestionDocentes.add(jMenuItemAgregarDocente);

        jMenuItemDocentesRegistrados.setText("Administrar Docentes");
        jMenuItemDocentesRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDocentesRegistradosActionPerformed(evt);
            }
        });
        jMenuGestionDocentes.add(jMenuItemDocentesRegistrados);

        JMenuInicio.add(jMenuGestionDocentes);

        jMenuGestionClases.setText("Gestionar Cursos");
        JMenuInicio.add(jMenuGestionClases);

        jMenuGestionAlumnos.setText("Gestionar Alumnos");
        JMenuInicio.add(jMenuGestionAlumnos);

        jMenuGestionActividades.setText("Gestionar Actividades");
        JMenuInicio.add(jMenuGestionActividades);

        JMenuItemSalir.setMnemonic('x');
        JMenuItemSalir.setText("Salir");
        JMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemSalirActionPerformed(evt);
            }
        });
        JMenuInicio.add(JMenuItemSalir);

        menuBar.add(JMenuInicio);

        JMenuAjustes.setMnemonic('e');
        JMenuAjustes.setText("Ajustes");

        JMenuItemCambiarColor.setMnemonic('t');
        JMenuItemCambiarColor.setText("Cambiar color de Fondo");
        JMenuAjustes.add(JMenuItemCambiarColor);

        menuBar.add(JMenuAjustes);

        JMenuAdministrar.setMnemonic('h');
        JMenuAdministrar.setText("Administrar Cuenta");

        JMenuItemActualizarDatos.setMnemonic('c');
        JMenuItemActualizarDatos.setText("Actualizar Datos");
        JMenuAdministrar.add(JMenuItemActualizarDatos);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Cambiar Contraseña");
        JMenuAdministrar.add(aboutMenuItem);

        jMenuItemEliminarCuenta.setText("Eliminar mi Cuenta");
        JMenuAdministrar.add(jMenuItemEliminarCuenta);

        menuBar.add(JMenuAdministrar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMenuItemSalirActionPerformed

    private void jMenuItemAgregarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarDocenteActionPerformed
        // TODO add your handling code here:
        jDesktopPaneEscritorio.add(ventanaRegistroDocente);
        ventanaRegistroDocente.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarDocenteActionPerformed

    private void jMenuItemDocentesRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDocentesRegistradosActionPerformed
        // TODO add your handling code here:
        jDesktopPaneEscritorio.add(ventanaGestionDocentes);
        ventanaGestionDocentes.cargarDatosTabla(controladorDocente.getListado());
        ventanaGestionDocentes.setVisible(true);
    }//GEN-LAST:event_jMenuItemDocentesRegistradosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAdministrar;
    private javax.swing.JMenu JMenuAjustes;
    private javax.swing.JMenu JMenuInicio;
    private javax.swing.JMenuItem JMenuItemActualizarDatos;
    private javax.swing.JMenuItem JMenuItemCambiarColor;
    private javax.swing.JMenuItem JMenuItemSalir;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane jDesktopPaneEscritorio;
    private javax.swing.JMenu jMenuGestionActividades;
    private javax.swing.JMenu jMenuGestionAlumnos;
    private javax.swing.JMenu jMenuGestionClases;
    private javax.swing.JMenu jMenuGestionDocentes;
    private javax.swing.JMenuItem jMenuItemAgregarDocente;
    private javax.swing.JMenuItem jMenuItemDocentesRegistrados;
    private javax.swing.JMenuItem jMenuItemEliminarCuenta;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
